name: CI/CD Pipeline for Derivatives Pricer

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # These are the permissions the workflow needs to talk to AWS.
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      # This action uses our secrets to securely log in to AWS.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 # IMPORTANT: Use the region where your ECR is!

      # More steps will be added here tomorrow...